Fix compilation error: undefined signOutput variable
Changed `signOutput, err =` to `signOutput, err :=` since signOutput
is a new variable in that scope.